"""Package a finished job's Ren'Py project as a downloadable zip."""

import json
import re
import zipfile

from . import jobs

HOW_TO_PLAY = """HOW TO PLAY
===========

This folder is a complete Ren'Py project generated by Once Upon a Line,
an autonomous AI showrunner agent.

1. Download the free Ren'Py SDK from https://www.renpy.org/latest.html
   (Windows / macOS / Linux).
2. Unzip this archive. Put the "{name}" folder inside the Ren'Py
   "Projects Directory" (the launcher shows/creates it on first start,
   or use the launcher's preferences to point at any folder).
3. Open the Ren'Py Launcher, select "{name}", click Launch Project.

Your choices during playback change how the story unfolds - play it twice!

Generated end-to-end by AI: screenplay, scene graph, keyframes, video clips,
character voice, subtitles and this project were all produced by Qwen models.
"""


def _slug(title):
    s = re.sub(r"[^A-Za-z0-9]+", "_", title or "interactive_story").strip("_")
    return s[:40] or "interactive_story"


def package(job_id):
    """Zip renpy_project/ as <TitleSlug>/... plus HOW_TO_PLAY.txt. Returns path."""
    d = jobs.job_dir(job_id)
    project = d / "renpy_project"
    if not project.is_dir():
        raise RuntimeError("no renpy_project to package")

    title = None
    scenes = d / "build" / "scenes.json"
    if scenes.exists():
        title = json.loads(scenes.read_text(encoding="utf-8")).get("title")
    name = _slug(title)

    zip_path = d / "game.zip"
    tmp = d / "game.zip.tmp"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(project.rglob("*")):
            if not f.is_file():
                continue
            rel = f.relative_to(project)
            if rel.parts[0] in ("cache", "saves") or f.suffix == ".rpyc":
                continue
            if f.suffix == ".webm" and f.stat().st_size == 0:
                raise RuntimeError(f"refusing to package 0-byte movie: {rel}")
            z.write(f, f"{name}/{rel.as_posix()}")
        z.writestr(f"{name}/HOW_TO_PLAY.txt", HOW_TO_PLAY.format(name=name))
    tmp.replace(zip_path)
    return zip_path
